hydra:

  launcher:
    timeout_min: 1440
    cpus_per_task: 32
    mem_gb: null
    nodes: 1
    constraint: a100

  sweeper:
    params:
      learning_rate: 2.5e-4
      num_steps: 32, 64, 128
      num_envs: 128, 256, 512, 1024
      num_minibatches: 4, 8, 16
  job:
    env_set:
      XLA_PYTHON_CLIENT_MEM_FRACTION: .49


defaults:
  - _self_ 
  - override hydra/launcher: submitit_slurm


env: pong
seed: 0
num_seeds: 8
num_envs: 32
num_steps: 128
num_epochs: 4
num_minibatches: 32
learning_rate: 1e-3
total_timesteps: 1000000
eval_freq: 65536
