hydra:

  launcher:
    timeout_min: 1440
    cpus_per_task: 24
    mem_gb: null
    nodes: 1
    constraint: a100

  sweeper:
    params:
      env: pong, airplane, blinky, brix, deep, filter, flight_runner, missile, rocket, shooting_stars, spacejam, squash, submarine, tank, tetris, ufo, vertical_brix, wipe_off, worm

  job:
    env_set:
      XLA_PYTHON_CLIENT_MEM_FRACTION: .49


defaults:
  - _self_ 
  - override hydra/launcher: submitit_slurm


env: pong
seed: 0
num_seeds: 12
num_envs: 512
num_steps: 32
num_epochs: 4
num_minibatches: 32
learning_rate: 5e-4
total_timesteps: 5000000
eval_freq: 131072
